#!/bin/bash

echo " ====Bienvenido a la Loteria de Loeches==="
echo " Elija un numero del 1 al 20 para poder ganar el sorteo"

premio=$(( RANDOM % 20 +1 ))


while true; do
  read -p "Dame un numero del 1 al 20: " numero
  if [[ $numero -gt 1 && $numero -lt 20 ]]; then

     if [ $numero -eq $premio ]; then
         echo "Has ganado la loteria"
     else
        echo "Sigue intentandolo"
     fi

 else

    echo "Error, introduce un numero del 1 al 20"
 fi

done
